# mkdocs.yml file

## Site

site_name: Nexus Play

## Configuration to watch

watch:
  - 'mkdocs.yml'
  - 'docs'

## Nav links

nav:
  - Home: index.md
  # - Visuals: 
  #     - 
  - Guides:
    - Introducción: guides/intro.md
    - Documentación de Usuario: guides/users.md
    - Documentación de Instalación: guides/install.md
    - Guía de Desarrollo: guides/development.md
    - Guía de Producción: guides/production.md
    - Estilos y UI/UX: guides/styles.md
    - Documentación de la Base de Datos: guides/database.md
    - Arquitectura del Sistema: guides/architecture.md
    - API: guides/api.md
    - Resolución de Problemas: guides/troubleshooting.md
    - Contribuir al Proyecto: guides/contributing.md

## Theme

theme: 
  name: mkdocs
  locale: es
  user_color_mode_toggle: true
  color_mode: auto
  nav_style: dark
  highlightjs: true
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'

## Metadata

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

## Links and scripts

# extra_css:
#   - 'stylesheets/extra.css'  # Puedes añadir tus propias hojas de estilo adicionales

# extra_javascript:
#   - 'javascripts/extra.js'  # Puedes añadir tus propios archivos JavaScript adicionales